import { Question, FormData } from '@/types'

export const questions: Question[] = [
  {
    id: 'name',
    title: 'What is your name?',
    type: 'text',
    field: 'name',
    required: true,
  },
  {
    id: 'mobile',
    title: 'What is your mobile number?',
    type: 'number',
    field: 'mobile',
    required: true,
  },
  {
    id: 'dob',
    title: 'What is your date of birth?',
    type: 'date',
    field: 'dob',
    required: true,
  },
  {
    id: 'gender',
    title: 'What is your gender?',
    type: 'radio',
    field: 'gender',
    options: ['Male', 'Female', 'Other'],
    required: true,
  },
  {
    id: 'employmentType',
    title: 'What is your employment type?',
    type: 'radio',
    field: 'employmentType',
    options: ['Salaried', 'Business'],
    required: true,
  },
  {
    id: 'companyName',
    title: 'What is your company name?',
    type: 'text',
    field: 'companyName',
    required: true,
  },
  {
    id: 'monthlyIncome',
    title: 'What is your monthly income?',
    type: 'dropdown',
    field: 'monthlyIncome',
    options: ['10k-25k', '25k–50k', '50k–100k', '1L+'],
    required: true,
  },
  {
    id: 'houseType',
    title: 'Do you own or rent your house?',
    type: 'radio',
    field: 'houseType',
    options: ['Own', 'Rented'],
    required: true,
  },
  {
    id: 'familyMembers',
    title: 'Select your family members',
    type: 'checkbox',
    field: 'familyMembers',
    options: ['Father', 'Mother', 'Spouse', 'Kids'],
    required: true,
  },
  {
    id: 'twoWheelersCount',
    title: 'How many 2-wheelers do you have?',
    type: 'dropdown',
    field: 'twoWheelersCount',
    options: ['0', '1', '2', '3', '4', '5'],
    required: true,
  },
  {
    id: 'twoWheelerInsurance',
    title: 'Do you have 2-wheeler insurance?',
    type: 'radio',
    field: 'twoWheelerInsurance.hasInsurance',
    options: ['Yes', 'No'],
    required: true,
    condition: (data: FormData) => Number(data.twoWheelersCount) > 0,
  },
  {
    id: 'fourWheelersCount',
    title: 'How many 4-wheelers do you have?',
    type: 'dropdown',
    field: 'fourWheelersCount',
    options: ['0', '1', '2', '3', '4', '5'],
    required: true,
  },
  {
    id: 'fourWheelerInsurance',
    title: 'Do you have 4-wheeler insurance?',
    type: 'radio',
    field: 'fourWheelerInsurance.hasInsurance',
    options: ['Yes', 'No'],
    required: true,
    condition: (data: FormData) => Number(data.fourWheelersCount) > 0,
  },
  {
    id: 'healthInsurance',
    title: 'Do you have health insurance?',
    type: 'radio',
    field: 'healthInsurance.hasInsurance',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'termInsurance',
    title: 'Do you have term insurance?',
    type: 'radio',
    field: 'termInsurance.hasInsurance',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'lifeInsurance',
    title: 'Do you have life insurance?',
    type: 'radio',
    field: 'lifeInsurance.hasInsurance',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'personalLoan',
    title: 'Do you have a personal loan?',
    type: 'radio',
    field: 'loans.personalLoan.hasLoan',
    options: ['Yes', 'No'],
    required: true,
    condition: (data: FormData) => data.employmentType === 'Salaried',
  },
  {
    id: 'twoWheelerLoan',
    title: 'Do you have a two-wheeler loan?',
    type: 'radio',
    field: 'loans.twoWheelerLoan.hasLoan',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'carLoan',
    title: 'Do you have a car loan?',
    type: 'radio',
    field: 'loans.carLoan.hasLoan',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'homeLoan',
    title: 'Do you have a home loan?',
    type: 'radio',
    field: 'loans.homeLoan.hasLoan',
    options: ['Yes', 'No'],
    required: true,
  },
  {
    id: 'businessLoan',
    title: 'Do you have a business loan?',
    type: 'radio',
    field: 'loans.businessLoan.hasLoan',
    options: ['Yes', 'No'],
    required: true,
    condition: (data: FormData) => data.employmentType === 'Business',
  },
  {
    id: 'creditCards',
    title: 'Do you have credit cards?',
    type: 'radio',
    field: 'creditCards.hasCards',
    options: ['Yes', 'No'],
    required: true,
  },
]